In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix, roc_curve,classification_report

In [2]:
root_dir = os.path.dirname(os.getcwd())
model_path = os.path.join(root_dir, 'models', 'mobilenetv2_ver_1.0.h5')
model = tf.keras.models.load_model(model_path)

In [3]:
test_datagen = ImageDataGenerator(rescale = 1./255)

test_dir = os.path.join('data', 'test')

test_generator = test_datagen.flow_from_directory(test_dir, target_size = (224,224), class_mode = 'categorical', batch_size = 20,shuffle=False)

Found 189 images belonging to 4 classes.


In [4]:
#Confution Matrix and Classification Report
num_of_test_samples = test_generator.n
batch_size = test_generator.batch_size
Y_pred = model.predict(test_generator, num_of_test_samples // batch_size+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(test_generator.classes, y_pred))
print('Classification Report')
target_names = ['None', 'Paper', 'Rock', 'Scissors']
print(classification_report(test_generator.classes, y_pred, target_names=target_names))

Confusion Matrix
[[38  1  0  0]
 [ 0 46  1  0]
 [ 0  0 57  0]
 [ 0  0  0 46]]
Classification Report
              precision    recall  f1-score   support

        None       1.00      0.97      0.99        39
       Paper       0.98      0.98      0.98        47
        Rock       0.98      1.00      0.99        57
    Scissors       1.00      1.00      1.00        46

    accuracy                           0.99       189
   macro avg       0.99      0.99      0.99       189
weighted avg       0.99      0.99      0.99       189

